name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -r requirements.txt
    - run: rm -rf /home/runner/work/team-3-project/team-3-project/node_modules
    - name: Install NPM dependencies
      run: npm install
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS Authentication
      run: serverless config credentials --provider aws --key ${{ secrets.ACCESS_KEY_ID }} --secret ${{ secrets.SECRET_KEY }}
    - run: sls deploy
